service: api
runtime: go112
env: standard
handlers:
- url: .*
  script: auto
  secure: always
automatic_scaling:
  min_idle_instances: automatic
  max_idle_instances: automatic
  min_pending_latency: automatic
  max_pending_latency: automatic
network: {}