service: docs
runtime: nodejs12
env: standard
default_expiration: 365d
automatic_scaling:
  min_idle_instances: automatic
  max_idle_instances: automatic
  min_pending_latency: automatic
  max_pending_latency: automatic
