name: 'Nodejs App'
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@master
        with:
          node-version: 12
      - uses: actions/checkout@master
    - run: npm install ./AppEngine/ipengine.dev/
    - run: npm run ./AppEngine/ipengine.dev/
